#!/bin/sh

. $(dirname "$0")/../init.sh

clear
# OCAK "$_OCAK_INTRO" "$_OCAK_OWN" "" "RUN COMMAND TO CONTAINER:" ">> $APP_NAME" "service memcached restart"
OCAK "$_OCAK_INTRO" "$_OCAK_OWN" "" "RUN COMMAND TO CONTAINER:" ">> ssz_one_memcached" "service memcached restart"
BR

# docker exec -it $APP_CONTAINER /etc/init.d/memcached restart
docker restart ssz_one_memcached
